# 多学科 + 多主题示例
categories: ["cs.CV", "cs.LG", "cs.CL"]
keywords:
  - "open vocabulary segmentation"
  - "referring segmentation"
  - "vision-language segmentation"
  - "vision language model"
  - "VLM"
  - "visual instruction tuning"
  - "vision-language alignment"
  - "training-free"
  - "zero-shot"
  - "test-time adaptation"
  - "prompt tuning"
  - "LoRA"

logic: "OR"                 # 组间逻辑：categories 与 keywords 间 AND/OR
max_results: 30
sort_by: "submittedDate"     # 或 lastUpdatedDate
sort_order: "descending"

# —— 新增：语言设置 ——
# zh / en / both
lang: "both"

# —— 新增：摘要设置 ——
# mode: none / heuristic / llm
summary:
  mode: llm # mode: "heuristic"
  # scope: tldr / full / both
  scope: "both"

# —— 新增：邮件发送（QQ 邮箱示例） ——
email:
  enabled: true
  subject: "[arXiv] Daily Digest"
  smtp_server: "smtp.qq.com"
  smtp_port: 465
  smtp_pass_env: "SMTP_PASS"
  tls: "auto"  # auto / ssl / starttls
  debug: false     # true 可打印 SMTP 调试日志（排障）
  detail: "full"  # simple / full
  max_items: 20
  attach_md: ture  # 是否开启Markdown附件
  attach_pdf: false  # 是否开启PDF附件

# —— 新增：LLM（DeepSeek/OpenAI 兼容） ——
llm:
  provider: "openai-compatible"     # 兼容 OpenAI SDK 的服务
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  api_key_env: "DS_API_KEY"
  system_prompt_en: |
    You are a senior paper-reading assistant. Based on the given metadata and abstract,
    write ONE concise paragraph in English that covers: research motivation, main method,
    and key experimental findings. Be objective and specific; avoid marketing language.
    Preserve any provided links, but do NOT repeat them in the paragraph.
  system_prompt_zh: |
    你是资深论文阅读助手。基于给定的论文元信息与摘要，用中文写「一段」简洁的总结，
    包含研究动机、核心方法与关键实验结果。保持客观、术语准确；避免营销式表述。
    如有链接请保留，但不要在总结里重复链接。
# —— 新增：中文翻译设置（用 LLM 翻译 title/summary） ——
translate:
  enabled: true         # 是否启用
  lang: "zh"            # 目前只需中文；也可扩展 en/ja 等
  fields: ["title", "summary"]   # 可扩：["title","summary","comments"]

site:
  enabled: true
  dir: "docs" # GitHub Pages 推荐用 docs 目录
  title: "arXiv 论文速递"
  keep_runs: 1024         # 历史保留期（按页面份数）
  theme: "light"        # "light" | "dark" | "auto"
  accent: "#2563eb"     # 主题色（可自定义）
