# 多学科 + 多主题示例
categories: ["cs.CV", "cs.LG", "cs.CL"]
keywords:
  - "open vocabulary segmentation"
  - "referring segmentation"
  - "vision-language segmentation"

logic: "OR"                 # 组间逻辑：categories 与 keywords 间 AND/OR
max_results: 10
sort_by: "submittedDate"     # 或 lastUpdatedDate
sort_order: "descending"

# —— 新增：语言设置 ——
# zh / en / both
lang: "both"

# —— 新增：摘要设置 ——
# mode: none / heuristic / llm
summary:
  mode: llm
  # mode: "heuristic"
  # scope: tldr / full / both
  scope: "both"

# —— 新增：邮件发送（QQ 邮箱示例） ——
email:
  enabled: true
  subject: "[arXiv] Daily Digest"
  smtp_server: "smtp.qq.com"
  smtp_port: 465
  smtp_pass_env: "SMTP_PASS"
  tls: "auto"  # auto / ssl / starttls
  debug: false     # true 可打印 SMTP 调试日志（排障）
  detail: "full"  # simple / full
  max_items: 20
  attach_md: Ture  # 是否关闭Markdown附件
  attach_pdf: false  # 是否关闭PDF附件

# —— 新增：LLM（DeepSeek/OpenAI 兼容） ——
llm:
  provider: "openai-compatible"     # 兼容 OpenAI SDK 的服务
  base_url: "https://api.deepseek.com"
  model: "deepseek-chat"
  api_key_env: "DS_API_KEY"
  system_prompt_zh: |
    你是资深论文阅读助手。请基于提供的论文元数据与摘要，输出中文 TL;DR 与“方法卡 + 讨论问题”。保留所有给定链接。
  system_prompt_en: |
    You are a seasoned paper-reading assistant. Based on the given paper metadata and abstract, produce an English TL;DR and a "Method Card + Discussion Questions". Preserve all provided links.
# —— 新增：中文翻译设置（用 LLM 翻译 title/summary） ——
translate:
  enabled: true         # 是否启用
  lang: "zh"            # 目前只需中文；也可扩展 en/ja 等
  fields: ["title", "summary"]   # 可扩：["title","summary","comments"]

site:
  enabled: true
  dir: "docs" # GitHub Pages 推荐用 docs 目录
  title: "arXiv 论文速递"
  keep_runs: 1024         # 历史保留期（按页面份数）
  theme: "light"        # "light" | "dark" | "auto"
  accent: "#2563eb"     # 主题色（可自定义）
